title: Tanzeem Ahmed
description: Personal site of Tanzeem Ahmed – Young Entrepreneur from Bangladesh
url: "https://tanzeemahmedentrepreneur.github.io/tanzeemahmed"
baseurl: ""

# Optional: Use a minimal theme OR define your own layout files
# If using custom layouts, comment out the next line
theme: jekyll-theme-cayman

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: Tanzeem Ahmed
  email: tanzeemahmed777@gmail.com

social:
  name: Tanzeem Ahmed
  links:
    - https://www.facebook.com/tanzeem.ahmed.sakib
    - https://www.instagram.com/tanzeem.ahmed_sadman
    - https://www.linkedin.com/in/tanzeem-ahmed-sakib/
