# _config.yml
title: Tanzeem Ahmed
description: "16-year-old Entrepreneur | Founder of Gadget Bikreta and ThreadVerse Co."
theme: jekyll-theme-cayman

social_links:
  - icon: "fa fa-facebook"
    url: "https://facebook.com/tanzeem.ahmed.sakib"
  - icon: "fa fa-instagram"
    url: "https://instagram.com/tanzeem.ahmed_sadman"
  - icon: "fa fa-linkedin"
    url: "https://www.linkedin.com/in/tanzeem-ahmed-sakib/"

paginate: 5
paginate_path: "/page:num/"
