title: "Tanzeem Ahmed"
description: "Entrepreneur | Founder of Gadget Bikreta & Thread Verse Co."
url: "https://tanzeemahmed.github.io"
baseurl: ""
author:
  name: "Tanzeem Ahmed"
  avatar: "/assets/images/tanzeem.jpg"
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-seo-tag
