title: Tanzeem Ahmed
description: Personal site of Tanzeem Ahmed – Young Entrepreneur from Bangladesh
url: "https://github.com/TanzeemAhmedEntrepreneur/tanzeemahmed"
baseurl: ""

theme: jekyll-theme-cayman

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: Tanzeem Ahmed
  email: tanzeemahmed777@gmail.com

social:
  name: Tanzeem Ahmed
  links:
    - https://www.facebook.com/tanzeem.ahmed.sakib
    - https://www.instagram.com/tanzeem.ahmed_sadman
    - https://www.linkedin.com/in/tanzeem-ahmed-sakib/
