# _config.yml
title: Tanzeem Ahmed
description: Personal site of Tanzeem Ahmed – Young Entrepreneur from Bangladesh
url: "https://tanzeemahmedentrepreneur.github.io/tanzeemahmed/"
baseurl: "" # leave empty for root

theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: Tanzeem Ahmed
  email: tanzeemahmed777@gmail.com

# SEO settings
social:
  name: Tanzeem Ahmed
  links:
- [Facebook](https://www.facebook.com/tanzeem.ahmed.sakib)
- [Instagram](https://www.instagram.com/tanzeem.ahmed_sadman)
- [LinkedIn](https://www.linkedin.com/in/tanzeem-ahmed-sakib/)

